version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/project/public:cached
    links:
      - api_assignment
    networks:
      - frontend
  api_assignment:
    container_name: api-test-project
    build: ./
    volumes:
      - ./:/project:cached
    working_dir: /project
    networks:
      - frontend
      - backend
    environment:
      APP_ENV: local
      APP_KEY: "base64:05VNDWbv5axaVCzWrtTBLMV1T1Ex8ML4dNzWINrWXHY="
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: api_assignment_db
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0.24
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api_assignment_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./:/project:ro
    working_dir: /project
    networks:
      - backend

networks:
  frontend:
  backend:
